### PR TITLE
fetch upstream from metamask

### PR DESCRIPTION
**Pull request by luckywebdev**
Fixes: #

Explanation:  

Manual testing steps:  
  - 
  - 
  -

### CODE REVIEW

**Comment by SebSeb11** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by daniiba** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Jordon-L** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Hyun2** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
